=== yurijserrano/ParidadeEmJava/jpacs2/files/JPACS.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT JPACS (config,relatorio*)>

<!ELEMENT config (memoria)>
<!ATTLIST config
        nome CDATA #IMPLIED>

<!ELEMENT memoria (principal,cache)>

<!ELEMENT principal EMPTY>
<!ATTLIST principal
        tamanho CDATA #REQUIRED
	     tempoacesso CDATA #REQUIRED>

<!ELEMENT cache ((lru|fifo),(sequencial|paralelo),(copyback|writethrought))>
<!ATTLIST cache
        tamanho CDATA #REQUIRED
  	     tempoacesso CDATA #REQUIRED
	     tamanhobloco CDATA #REQUIRED>

<!ELEMENT lru EMPTY>
<!ELEMENT fifo EMPTY>
<!ELEMENT sequencial EMPTY>
<!ELEMENT paralelo EMPTY>
<!ELEMENT copyback EMPTY>
<!ELEMENT writethrought EMPTY>

<!ELEMENT relatorio (acesso*,estatisticas)>
<!ATTLIST relatorio
	nome CDATA #IMPLIED>

<!ELEMENT acesso EMPTY>
<!ATTLIST acesso 
	numero CDATA #REQUIRED
	posicao CDATA #REQUIRED
	natureza (leitura|gravacao) #REQUIRED
	bloco CDATA #REQUIRED
	tempo CDATA #REQUIRED
	resultado (erro|acerto) #REQUIRED
	subs CDATA #IMPLIED>

<!ELEMENT estastisticas (principal,cache,total)>

<!ELEMENT memprincipal EMPTY>
<!ATTLIST memprincipal
	acessos CDATA #REQUIRED
	tempoacesso CDATA #REQUIRED
	tempototal CDATA #REQUIRED>

<!ELEMENT memcache EMPTY>
<!ATTLIST memcache
	acessos CDATA #REQUIRED
	tempoacesso CDATA #REQUIRED
	tempototal CDATA #REQUIRED
	taxaacerto CDATA #REQUIRED
	taxaerro CDATA #REQUIRED>

<!ELEMENT total EMPTY>
<!ATTLIST total
	comcache CDATA #REQUIRED
	semcache CDATA #REQUIRED
	ganho CDATA #REQUIRED>

=== yurijserrano/ParidadeEmJava/jpacs2/config/Cesar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE JPACS SYSTEM "JPACS.dtd">

<JPACS>
   <config nome="C:\Java\jpacs\Config\Cesar.xml">
	   <memoria>
		   <principal tamanho="1024" tempoacesso="100" />
		   <cache tamanho="3" tempoacesso="15" tamanhobloco="10">
                <fifo /> <paralelo /> <writethrought />
		    </cache>
    	 </memoria>
   </config>
</JPACS>

=== yurijserrano/ParidadeEmJava/jpacs2/config/Config1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE JPACS SYSTEM "JPACS.dtd">

<JPACS>
   <config nome="Config1.xml">
	   <memoria>
		   <principal tamanho="2048" tempoacesso="100" />
		   <cache tamanho="5" tempoacesso="15" tamanhobloco="10">
                <lru /> <sequencial /> <copyback />
		    </cache>
    	 </memoria>
   </config>
</JPACS>

=== yurijserrano/ParidadeEmJava/jpacs2/JPACS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE JPACS SYSTEM "JPACS.dtd">

<JPACS>
   <config nome="JPACS.xml">
	   <memoria>
		   <principal tamanho="1024" tempoacesso="100" />
		   <cache tamanho="5" tempoacesso="15" tamanhobloco="8">
                <fifo /> <paralelo /> <writethrought />
		    </cache>
    	 </memoria>
   </config>
</JPACS>

=== yurijserrano/ParidadeEmJava/jpacs2/config/Matriz.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE JPACS SYSTEM "JPACS.dtd">

<JPACS>
   <config nome="C:\Java\jpacs\Config\Matriz.xml">
	   <memoria>
		   <principal tamanho="1024" tempoacesso="150" />
		   <cache tamanho="15" tempoacesso="20" tamanhobloco="30">
                <lru /> <sequencial /> <writethrought />
		    </cache>
    	 </memoria>
   </config>
</JPACS>
